######################################################################
#																	 #
#				  XERIS/APEX System I, Release 1					 #
#																	 #
#						  XERIS	 CORE								 #
#					     FLATLINE%ULIF$								 #
#					    AVR5 UART DRIVER							 #
#																	 #
######################################################################


if.o: m5.S
	$(CC) $(CFLAGS) $(CPPFLAGS) $(TARGET_ARCH) -c -o $@ $<
